import type { JsonValue } from "../utils/custom-json-value"
import type { I18nText, PluginContext } from "./common"
import type { Property, PropertyScalar } from "./property"

export interface BaseDefinition {
  /**
   * Name
   */
  name: string
  /**
   * Display name
   */
  display_name: I18nText
  /**
   * Description
   */
  description: I18nText
  /**
   * Icon, allowed to use Emoji or URL address
   */
  icon: string
}

/**
 * Plugin definition
 */
export interface PluginDefinition<Locales extends string[], TransporterOptions>
  extends BaseDefinition {
  /**
   * The locales to support. Defaults to ["en_US"].
   */
  locales: Locales
  /**
   * The author's name of the plugin.
   */
  author?: string | null
  /**
   * The author's email address.
   */
  email?: string | null
  /**
   * The source URL of the plugin.
   */
  repo?: string | null
  /**
   * The version of the plugin.
   *
   * If you do not provide this value, it will fallback to the version field in your package.json file.
   *
   * We recommend doing it this way, but if you do provide this value, please ensure that it remains consistent with the version field in package.json.
   */
  version?: string | null
  /**
   * The options for the transporter.
   */
  transporterOptions?: TransporterOptions
  /**
   * The programming language the plugin is implemented in.
   */
  lang: "elixir" | "typescript"
}

export type Feature = CredentialDefinition | DataSourceDefinition | ModelDefinition | ToolDefinition

export type InputArgsCredential = Record<string, string | number | boolean | null | undefined>

/**
 * Credential definition
 */
export interface CredentialDefinition extends BaseDefinition {
  authenticate?: (input: {
    args: {
      credential: InputArgsCredential
      extra?:
        | {
            /**
             * If it is called for the LLM authentication, then this property is the model name.
             */
            model?: string | undefined
            [key: string]: unknown
          }
        | undefined
    }
    context: PluginContext
  }) => Promise<{
    /**
     * What kind of LLM provider is used.
     */
    adapter: "anthropic" | "openai" | "google_ai" | "deepseek"
    api_key: string
    endpoint?: string
    model?: string
    /**
     * The headers to be sent with the request.
     */
    headers?: Record<string, string>
    [key: string]: unknown
  }>
  /**
   * Whether this credential uses the OAuth2 authentication flow.
   *
   * When `true`, the Hub will invoke the `oauth2_build_authorize_url`, `oauth2_get_token`,
   * and `oauth2_refresh_token` callbacks to manage the OAuth2 lifecycle.
   */
  oauth2?: boolean
  /**
   * The OAuth2 grant type to use for this credential.
   * Callers must explicitly provide either `"authorization_code"` or `"client_credentials"`.
   */
  oauth2_grant_type: "authorization_code" | "client_credentials"
  /**
   * Build the OAuth2 authorization URL to redirect the user to for consent.
   *
   * Called by the Hub when initiating the OAuth2 authorization flow.
   * Must return a `{ url }` object containing the full authorization URL.
   */
  oauth2_build_authorize_url?: (input: {
    args: {
      credential: InputArgsCredential
      /** The redirect URI provided by the Hub for the OAuth2 callback. */
      redirect_uri: string
      /** The state parameter generated by the Hub (used for CSRF protection). */
      state: string
    }
    context: PluginContext
  }) => Promise<{ url: string }>
  /**
   * Exchange an authorization code for access/refresh tokens.
   *
   * Called by the Hub after the user completes the OAuth2 consent flow.
   * Must return a `{ parameters_patch }` map which will be merged into the credential's parameters.
   */
  oauth2_get_token?: (input: {
    args: {
      credential: InputArgsCredential
      /** The authorization code returned by the OAuth2 provider. */
      code: string
      /** The redirect URI used in the authorization request. */
      redirect_uri: string
    }
    context: PluginContext
  }) => Promise<{
    parameters_patch: {
      access_token: string
      refresh_token: string
      /**
       * The unix timestamp (in seconds) when the access token expires.
       *
       * When this value is provided (not null/undefined), the Hub will use it to
       * schedule automatic refresh of the access token via `oauth2_refresh_token`.
       */
      expires_at?: number | null | undefined
      [key: string]: unknown
    }
  }>
  /**
   * Refresh the access token using a refresh token.
   *
   * Called by the Hub's scheduled job when the access token is near expiry.
   * Must return a `{ parameters_patch }` map which will be merged into the credential's parameters.
   *
   * **Note:** The `expires_at` parameter (unix timestamp in seconds) controls when the Hub
   * schedules automatic token refresh. If the credential's parameters do not include `expires_at`,
   * the Hub will not trigger automatic refresh.
   */
  oauth2_refresh_token?: (input: {
    args: {
      credential: InputArgsCredential
    }
    context: PluginContext
  }) => Promise<{
    parameters_patch: {
      access_token: string
      /**
       * The unix timestamp (in seconds) when the access token expires.
       *
       * When this value is provided (not null/undefined), the Hub will use it to
       * schedule automatic refresh of the access token via `oauth2_refresh_token`.
       */
      expires_at?: number | null | undefined
      [key: string]: unknown
    }
  }>
  parameters: Array<PropertyScalar>
}

/**
 * DataSource definition
 */
export interface DataSourceDefinition extends BaseDefinition {
  parameters: Array<PropertyScalar>
}

/**
 * Model definition
 */
export interface ModelDefinition extends BaseDefinition {
  /**
   * The unique name of the model.
   *
   * Plugin authors should use the **"model_provider/model_name"** format to define this field.
   */
  name: string // NOTE: Do not define it as a template literal, use zod schema instead
  /**
   * The type of the model, currently only "llm" is supported.
   */
  model_type: "llm"
  /**
   * The default endpoint of the model.
   */
  default_endpoint?: string | null
  /**
   * Supported input types.
   */
  input_modalities: Array<"file" | "image" | "text">
  /**
   * Supported output types.
   */
  output_modalities: Array<"text">
  /**
   * All pricing values is in currency (if specified) per token/request.
   *
   * A value of 0 means the feature is free.
   */
  pricing?: {
    /**
     * The currency of the pricing. Defaults to "USD" if not specified.
     */
    currency?: string | null
    /**
     * Cost per input token.
     */
    input?: number | null
    /**
     * Input cache read token price.
     */
    input_cache_read?: number | null
    /**
     * Input cache write token price.
     */
    input_cache_write?: number | null
    /**
     * Cost per output token.
     */
    output?: number | null
    /**
     * Fixed cost per API request if applicable.
     */
    request?: number | null
  } | null
  /**
   * Override the default parameters of the model.
   */
  override_parameters?: {
    /**
     * This setting influences the variety in the model’s responses. Lower values lead to more predictable and typical responses, while higher values encourage more diverse and less common responses. At 0, the model always gives the same response for a given input.
     */
    temperature?: {
      /**
       * @default 1.0
       */
      default?: number | null
      /**
       * @default 2.0
       */
      maximum?: number | null
      /**
       * @default 0.0
       */
      minimum?: number | null
    } | null
    /**
     * This setting aims to control the repetition of tokens based on how often they appear in the input. It tries to use less frequently those tokens that appear more in the input, proportional to how frequently they occur. Token penalty scales with the number of occurrences. Negative values will encourage token reuse.
     */
    frequency_penalty?: {
      /**
       * @default 0.0
       */
      default?: number | null
      /**
       * @default 2.0
       */
      maximum?: number | null
      /**
       * @default -2.0
       */
      minimum?: number | null
    } | null
    /**
     * This sets the upper limit for the number of tokens the model can generate in response. It won’t produce more than this limit. The maximum value is the context length minus the prompt length.
     */
    max_tokens?: {
      /**
       * @default 1_048_576
       */
      default?: number | null
      /**
       * @default 2_000_000
       */
      maximum?: number | null
    } | null
    /**
     * Constrains the verbosity of the model’s response. Lower values produce more concise responses, while higher values produce more detailed and comprehensive responses. Introduced by OpenAI for the Responses API.
     *
     * For Anthropic models, this parameter maps to `output_config.effort`.
     */
    verbosity?: {
      /**
       * @default "medium"
       */
      default?: "low" | "medium" | "high" | null
    } | null
  } | null
  /**
   * Declare which parameters are not supported by the model.
   *
   * Parameters defined here will not appear in the UI's parameter panel.
   *
   * Currently, the built-in parameters support are:
   * - endpoint
   * - temperature
   * - frequency_penalty
   * - seed
   * - max_tokens
   * - json_schema
   * - stream
   * - stream_options
   * - structured_outputs
   * - parallel_tool_calls
   * - verbosity
   */
  unsupported_parameters: Array<
    | "endpoint"
    | "temperature"
    // | "top_p"
    // | "top_k"
    | "frequency_penalty"
    // | "presence_penalty"
    // | "repetition_penalty"
    // | "min_p"
    // | "top_a"
    | "seed"
    | "max_tokens"
    // | "logit_bias"
    // | "logprobs"
    // | "top_logprobs"
    // | "response_format"
    // | "json_response"
    | "json_schema"
    | "stream"
    | "stream_options"
    | "structured_outputs"
    // | "stop"
    // | "tools"
    // | "tool_choice"
    | "parallel_tool_calls"
    | "verbosity"
  >
}

export type ToolLocatorListFunction = (input: {
  parameters: Record<string, unknown>
  credentials: Record<string, InputArgsCredential>
  filter?: string | null
  pagination_token?: string | null
}) => Promise<{
  results: {
    label: string
    value: string
    /**
     * external url related to the result
     */
    url?: string | null
  }[]
  pagination_token?: string | null
}>

export interface ToolResourceMappingField {
  id: string
  type: "string" | "number" | "boolean" | "object" | "array" | "integer"
  display_name?: I18nText | null
  required?: boolean | null
  ui?: {
    hint?: I18nText | null
  } | null
}

export type ToolResourceMappingFunction = (input: {
  args: {
    parameters: Record<string, unknown>
    credentials: Record<string, InputArgsCredential>
  }
}) => Promise<{
  fields: Array<ToolResourceMappingField>
  /**
   * The notice to be displayed when the resource mapping is empty.
   */
  empty_fields_notice?: I18nText | null | undefined
}>

/**
 * Tool definition
 */
export interface ToolDefinition extends BaseDefinition {
  /**
   * The function to invoke when the tool is called.
   *
   * **Caution for developers**: You must ensure that the return value is JSON serializable.
   */
  invoke: (input: {
    // biome-ignore lint/suspicious/noExplicitAny: Only tools knowns the args type.
    args: { parameters: Record<string, any>; credentials?: Record<string, InputArgsCredential> }
    context: PluginContext
  }) => Promise<JsonValue>
  parameters: Array<Property>
  locator_list?: Record<string, ToolLocatorListFunction> | null
  resource_mapping?: Record<string, ToolResourceMappingFunction> | null
  skill?: string | null
}
